baseURL: https://lesdictonsderiton.netlify.app/
languageCode: fr-FR
defaultContentLanguage: fr
title: Les dictons de Riton
theme: papercss-hugo-theme
googleAnalytics: G-0JKWL16MPB 
disqusShortname: yourdiscussshortname

privacy:
  disqus:
    disable: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  homeMetaContent: A Hugo theme made with PaperCSS, the less formal CSS framework.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2 Jan 2006
  navTitleLink: /

menu:
  nav:
    - name: Dictons
      url: /
      weight: 1
    - name: Chansons
      url: /chansons/
      weight: 2
    - name: Blagues
      url: /blagues/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4 
    - name: A propos
      url: /apropos/
      weight: 5 
    # - name: RSS
    #   url: /index.xml
    #   weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
